### ISSUE TITLE
Use minijax app with a servlet container

### ISSUE THREAD

**Issue by deepakmn** [minijax/minijax#14]
Is it possible to build a minijax application for the servlet container? What changes would be required? My current servlet container is Tomcat 7 (used at customer site).

**Comment by codyebberson** [comment]
Hi @deepakmn, thanks for looking at minijax.

I added a servlet container example here:
https://github.com/minijax/minijax/tree/master/minijax-examples/minijax-example-servlet

Let me know if you have any questions
